### ISSUE TITLE
`rewards-server`: Milestones 

### ISSUE THREAD

**Issue by chowder** [chowder/ttv-cli#17]
- [x] Allow one server to serve multiple streamers through multiple `Hub`s 
- [x] Include redemption thumbnail in the UI 
- [x] Deploy on Fly.io 
- [x] Create simple Docker image for the app

**Comment by chowder** [comment]
Implemented in https://github.com/chowder/ttv-cli/commit/4d3031d67c0115ad74887c7a5f34a3534b0c1972

**Comment by chowder** [comment]
Impleneted in https://github.com/chowder/ttv-cli/commit/74d52494de4143e6d4d6d5c18daec7394787b0e0
